source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

use_frameworks!

target 'Ursus Demo' do
    pod 'Ursus', path: '..'
    pod 'Ursus/Utilities', path: '..'
    pod 'AlamofireLogger', '~> 0.3'
end
