//
//  Error.swift
//  Ursus
//
//  Created by Daniel Clelland on 7/08/16.
//  Copyright © 2016 Daniel Clelland. All rights reserved.
//

import Foundation

/// Helper struct for creating Ursus errors.
public struct Error {
    
    /// The Ursus error domain.
    public static let domain = "com.ursus.error"
    
    /// An error code generated by Ursus.
    public enum Code: Int {
        
        /// An error code for the case where no base url was set in the core Ursus class.
        case NoBaseURLSpecified
        
        /// The error code's pretty printed description.
        private var localizedDescription: String {
            switch self {
            case .NoBaseURLSpecified:
                return "No base URL specified. Please set the baseURL property on the Ursus client."
            }
        }
    }
    
    /**
     Creates an Ursus error object.
     
     - code: The Ursus error code.
     
     - returns: An NSError object.
     */
    public static func error(withCode code: Code) -> NSError {
        return NSError(domain: domain, code: code.rawValue, userInfo: [NSLocalizedFailureReasonErrorKey: code.localizedDescription])
    }
    
}